import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#FAF9FA',
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 48,
    alignItems: 'center',
  },
  // Desktop styles
  desktopContainer: {
    flex: 1,
    flexDirection: 'row',
    maxWidth: 1100,
    width: '100%',
    alignSelf: 'center',
  },
  desktopBrandingColumn: {
    flex: 1,
    backgroundColor: '#111',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 48,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  desktopBrandingContent: {
    maxWidth: 400,
    alignItems: 'center',
  },
  desktopBrandingLogo: {
    width: 120,
    height: 120,
    marginBottom: 24,
    tintColor: '#fff',
  },
  desktopBrandingTitle: {
    fontSize: 42,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 16,
    textAlign: 'center',
  },
  desktopBrandingTagline: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    lineHeight: 28,
    marginBottom: 32,
  },
  desktopFeatureList: {
    gap: 16,
    width: '100%',
  },
  desktopFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  desktopFeatureIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  desktopFeatureText: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.9)',
  },
  desktopFormColumn: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 48,
    backgroundColor: '#FAF9FA',
  },
  desktopFormCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 40,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  desktopFormTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#111',
    marginBottom: 8,
    textAlign: 'center',
  },
  desktopFormSubtitle: {
    fontSize: 15,
    color: '#666',
    textAlign: 'center',
    marginBottom: 32,
  },
  desktopProviderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#ddd',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  desktopProvidersContainer: {
    gap: 14,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 48,
  },
  logoIcon: {
    width: 96,
    height: 96,
    marginBottom: 16,
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#111',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
  },
  providersContainer: {
    width: '100%',
    maxWidth: 320,
    gap: 12,
  },
  providerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  providerButtonDisabled: {
    opacity: 0.5,
  },
  githubButton: {
    backgroundColor: '#24292e',
    borderColor: '#24292e',
  },
  googleButton: {
    backgroundColor: '#fff',
    borderColor: '#ddd',
  },
  providerIcon: {
    width: 20,
    height: 20,
  },
  providerText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111',
  },
  githubText: {
    color: '#fff',
  },
  googleText: {
    color: '#111',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: 320,
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#ddd',
  },
  dividerText: {
    paddingHorizontal: 16,
    fontSize: 13,
    color: '#888',
  },
  comingSoon: {
    fontSize: 11,
    color: '#888',
    marginLeft: 8,
  },
});
