import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FAF9FA' },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
    alignItems: 'center',
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    alignItems: 'center',
  },
  // Desktop: two-column layout
  desktopContainer: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 48,
    paddingTop: 48,
    maxWidth: 1200,
    width: '100%',
    alignSelf: 'center',
  },
  // Left side: branding + main actions
  heroSection: {
    flex: 1,
    justifyContent: 'center',
    paddingRight: 48,
  },
  // Right side: queue lists
  queuesSection: {
    flex: 1,
    paddingLeft: 48,
    borderLeftWidth: 1,
    borderLeftColor: '#e6e6e6',
    justifyContent: 'center',
  },
  innerContainer: {
    width: '100%',
    maxWidth: 480,
    alignItems: 'center',
  },
  returnButton: {
    marginTop: 12,
    width: '100%',
    backgroundColor: '#2ea44f',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  returnButtonSpacing: {
    marginTop: 10,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    marginBottom: 32,
  },
  titleContainerDesktop: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: 0,
    marginBottom: 40,
  },
  logoIcon: {
    width: 128,
    height: 128,
    marginRight: 16,
  },
  logoIconDesktop: {
    width: 80,
    height: 80,
    marginRight: 0,
    marginBottom: 16,
  },
  title: {
    fontSize: 56,
    fontWeight: '700',
    lineHeight: 64,
  },
  titleDesktop: {
    fontSize: 48,
    lineHeight: 56,
  },
  tagline: {
    fontSize: 18,
    color: '#555',
    marginTop: 12,
    lineHeight: 26,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 20,
  },
  buttonRowDesktop: {
    flexDirection: 'column',
    gap: 12,
    width: '100%',
    maxWidth: 280,
  },
  button: {
    backgroundColor: '#111',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
    minWidth: 160,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  buttonDesktop: {
    minWidth: 200,
    paddingVertical: 16,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  joinedButton: {
    marginTop: 0,
    width: '100%',
    backgroundColor: '#fff',
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#2ea44f',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  joinedButtonText: {
    color: '#2ea44f',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  buttonSpacing: {
    marginTop: 10,
  },
  sectionContainer: {
    width: '100%',
    marginTop: 32,
  },
  sectionContainerDesktop: {
    marginTop: 0,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111',
    marginBottom: 12,
    textAlign: 'left',
    width: '100%',
  },
  queueCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    padding: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  queueCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
    marginBottom: 4,
  },
  queueCardSubtitle: {
    fontSize: 13,
    color: '#666',
  },
  emptyQueuesText: {
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
    paddingVertical: 24,
  },
  privacyLink: {
    marginTop: 32,
    fontSize: 12,
    color: '#555',
    textDecorationLine: 'underline',
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 24,
    marginTop: 32,
  },
  myQueuesButton: {
    marginTop: 20,
    width: '100%',
    backgroundColor: '#fff',
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#1f6feb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  myQueuesButtonDesktop: {
    marginTop: 12,
    maxWidth: 280,
  },
  myQueuesButtonText: {
    color: '#1f6feb',
    fontSize: 14,
    fontWeight: '600',
  },
});
