import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#FAF9FA',
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#111',
    marginBottom: 8,
  },
  periodSelector: {
    flexDirection: 'row',
    gap: 8,
  },
  periodButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#e5e5e5',
  },
  periodButtonActive: {
    backgroundColor: '#111',
  },
  periodButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666',
  },
  periodButtonTextActive: {
    color: '#fff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#666',
  },
  errorContainer: {
    padding: 20,
    backgroundColor: '#fee2e2',
    borderRadius: 12,
    marginBottom: 16,
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 14,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#b91c1c',
    borderRadius: 8,
    alignSelf: 'center',
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111',
    marginBottom: 12,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statItem: {
    flex: 1,
    minWidth: 100,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111',
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: '#666',
    marginTop: 4,
    textAlign: 'center',
  },
  funnelContainer: {
    gap: 8,
  },
  conversionWrapper: {
    gap: 14,
  },
  conversionSummary: {
    fontSize: 12,
    fontWeight: '600',
    color: '#444',
  },
  conversionStep: {
    gap: 6,
  },
  conversionStepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  conversionStepLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111',
  },
  conversionStepNumbers: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111',
  },
  conversionBarBase: {
    width: '100%',
    height: 24,
    borderRadius: 12,
    backgroundColor: '#e5e7eb',
    overflow: 'hidden',
    flexDirection: 'row',
  },
  conversionBarFill: {
    backgroundColor: '#3b82f6',
    borderRadius: 12,
  },
  conversionSegmentsRow: {
    flexDirection: 'row',
    width: '100%',
    height: 24,
    borderRadius: 12,
    overflow: 'hidden',
  },
  conversionSegment: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  segmentNotStarted: {
    backgroundColor: '#d1d5db',
  },
  segmentPending: {
    backgroundColor: '#3b82f6',
  },
  segmentCompleted: {
    backgroundColor: '#10b981',
  },
  segmentAbandoned: {
    backgroundColor: '#ef4444',
  },
  conversionSegmentText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#fff',
  },
  conversionLegendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    gap: 12,
  },
  conversionLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  conversionLegendSwatch: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  conversionLegendLabel: {
    fontSize: 11,
    color: '#444',
  },
  conversionStepRate: {
    fontSize: 11,
    fontWeight: '500',
    color: '#555',
  },
  conversionHelp: {
    fontSize: 10,
    color: '#888',
  },
  funnelItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  funnelBar: {
    height: 24,
    backgroundColor: '#3b82f6',
    borderRadius: 4,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  funnelBarValue: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  funnelLabel: {
    fontSize: 12,
    color: '#666',
    flex: 1,
  },
  funnelPercent: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111',
    width: 50,
    textAlign: 'right',
  },
  eventRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  eventType: {
    fontSize: 13,
    color: '#333',
    flex: 1,
  },
  eventCount: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111',
  },
  platformItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  platformIcon: {
    width: 24,
    height: 24,
    borderRadius: 4,
    backgroundColor: '#e5e5e5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  platformName: {
    fontSize: 14,
    color: '#333',
    flex: 1,
  },
  platformCount: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111',
  },
  chartContainer: {
    height: 120,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
    paddingTop: 8,
  },
  chartBar: {
    flex: 1,
    backgroundColor: '#3b82f6',
    borderRadius: 4,
    minHeight: 4,
  },
  chartLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  chartLabel: {
    fontSize: 10,
    color: '#999',
  },
  emptyState: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: '#999',
  },
  queueRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  queueHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  queueName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111',
    flex: 1,
    marginRight: 8,
  },
  queueCode: {
    fontSize: 12,
    fontWeight: '500',
    color: '#888',
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  queueStats: {
    flexDirection: 'row',
    gap: 12,
  },
  queueStatItem: {
    fontSize: 12,
    color: '#666',
  },
  etaNote: {
    fontSize: 11,
    color: '#666',
    marginTop: 12,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  completionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  completionBucket: {
    fontSize: 12,
    fontWeight: '500',
    color: '#333',
    width: 65,
  },
  completionBarContainer: {
    flex: 1,
    height: 16,
    backgroundColor: '#e5e7eb',
    borderRadius: 8,
    overflow: 'hidden',
  },
  completionBarFill: {
    height: '100%',
    backgroundColor: '#10b981',
    borderRadius: 8,
  },
  completionRate: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111',
    width: 36,
    textAlign: 'right',
  },
  completionCount: {
    fontSize: 11,
    color: '#888',
    width: 40,
    textAlign: 'right',
  },
  exportSection: {
    marginBottom: 20,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  exportTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    marginBottom: 10,
  },
  exportButtons: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  exportButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#111',
    borderRadius: 8,
  },
  exportButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
});
